[package]
name = "containers"
version = "0.1.0"
edition = "2024"

[dependencies]
# paste = "1.0.15"

# [lib]
# name = "containers"
# path = "src/lib.rs"

# [[bin]]
# name = "containers"
# path = "src/main.rs"
